steps:
  - name: maven:3.6.3-jdk-11
    entrypoint: mvn
    args: ["package","-DskipTests"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/postgres","."]
images: ['gcr.io/$PROJECT_ID/postgres']